### ISSUE TITLE
Allow Modules along with real subpages

### ISSUE THREAD

**Issue by mmoollllee** [medienbaecker/kirby-modules#30]
Hey there,

I hope I'm not getting something wrong here, but I see a "Modules" subpage when using the Modules Plugin along with real subpages and getting a redirect for those too.

<img width="1499" alt="Bildschirmfoto 2021-09-05 um 22 25 24" src="https://user-images.githubusercontent.com/26859300/132140628-f4d3fa86-32e1-4494-9168-e90bbe08f345.png">

Is this blueprint even possible?

```yml
  - width: 1/2
      sections:
        subpages:
          headline: Inhalte
          type: pages
  - width: 1/2
      sections:
        modules: true
```

**Comment by medienbaecker** [comment]
Yes, that's possible by limiting the templates for your regular pages section.

```yml
type: pages
templates:
  - default
  - contact
  - etc
```

It's currently not possible to hide a page without completely disabling the subpages — but the Kirby team is currently working on it: https://github.com/getkirby/kirby/pull/3621

**Comment by mmoollllee** [comment]
Yay! That does the job :)
Thank you!

**Comment by squareclouds** [comment]
hi everyone! it seems this does not work for the site.yml, here i am getting a sync between the modules and pages. in a regular page it works though. any ideas? all hlep is appreciated!

![Bildschirmfoto 2022-06-02 um 18 41 24](https://user-images.githubusercontent.com/9073054/171681282-f6832580-d01a-4920-b10c-a956b33b6cd3.png)

**Comment by squareclouds** [comment]
PS: oh i see now that i cannot even create modules for the site... this is probably per design?

**Comment by medienbaecker** [comment]
Yes, using modules in the `site.yml` doesn't work because it isn't a page.

I'm wondering if you'd rather want to use modules on the home page and display this section in the `site.yml`?

```yml
# site/blueprints/site.yml
sections:
  modules:
    parent: site.homePage.find('modules')
```

```yml
# site/blueprints/home.yml
sections:
  modules: true
```
