### ISSUE TITLE
[Kirby 3.6] Breadcrumb item not hidden

### ISSUE THREAD

**Issue by medienbaecker** [medienbaecker/kirby-modules#31]
## Bad news
The breadcrumb markup has been changed to an `<ol>` with wrapping `<li>` elements. This prevents this CSS to work:

```css
.k-topbar-crumbs a[href$="+modules"] {
  display: none;
}
```

## Good news
Once https://github.com/getkirby/kirby/pull/3621 is merged, `show: false` can be used instead.
