### ISSUE TITLE
❓ Easy way to limit module creation to certain templates in parent blueprint?

### ISSUE THREAD

**Issue by hariom147** [medienbaecker/kirby-modules#32]
```
modules: 
  templates: myTemplate
```
doesn't seem to work. Is there an easy way of adding this?

**Comment by medienbaecker** [comment]
You can add a `create` option to limit it to certain templates:

```yml
modules:
  type: modules
  create:
    - text
    - images
```
