### ISSUE TITLE
Error: Call to a member function url() on null

### ISSUE THREAD

**Issue by dustsucker** [medienbaecker/kirby-modules#38]
I tried to use the separate modules' folder approach, so I could use "global" Modules so making modules with site.yml and using them as blocks within every page I have so if I change something inside the module it applies to every page I use the module on the plugin seems perfect for that. The Problem I have is that the modules section is displayed, and I try to create a module with the normal add button so like a page select the Default Module Template I created, and it gives me the Error Message: Error: Call to a member function url() on null.

For context, the site.yml looks like this: 
```yml
# site/blueprints/site.yml
title: Site

columns:
  - width: 1/2
    sections:
        pages:
          type: pages
  - width: 1/2
    sections:
        modules: true
```

and the Default module like this:
```yml
# site/modules/default/default.yml
title:
  en: Module-Default
  de: Module-Default
fields:
  header:
    type: layout
    pretty: true
    layouts:
      - "1/1"
      - "1/2, 1/2"
    fieldsets:
      - heading
      - text
      - list
      - image
      - gallery
      - video
      - code
      - markdown
```

the section modules Displays the pages I already have:
![image](https://github.com/medienbaecker/kirby-modules/assets/17184952/7ca9ce9d-1dbe-4f78-86c7-8d3f699573c9)

And The error i get: 
![image](https://github.com/medienbaecker/kirby-modules/assets/17184952/997ecaba-50af-4b73-91f4-d2ec8a76a060)

I'm pretty sure it has something to do with a small error on my site, but I can't find it. Or is this not possible because it has to have a page as parent?
