### ISSUE TITLE
Possibility to define modules per section

### ISSUE THREAD

**Issue by tan3ot** [medienbaecker/kirby-modules#44]
It would be great to define possible modules in blueprint sections e.g.

```
modules:
  type: modules
  modules:
    - text
    - images
    - quote
```

Or have I overlooked something? Is that already possible?

**Comment by medienbaecker** [comment]
That's already possible. The modules plugin automatically populates the `create` option for the pages section, but you can overwrite it. Make sure to add the `module.` prefix to the options.

```yml
modules:
  create:
    - module.text
    - module.images
```
