### ISSUE TITLE
All modules vs selected modules

### ISSUE THREAD

**Issue by illycz** [medienbaecker/kirby-modules#9]
In docs, there is: "Every blueprint starting with `module.` is available to create".
Is it possible to set only some modules?
For example I need different modules for homepage and for blogposts.

Thanks

**Comment by medienbaecker** [comment]
I'm setting the `create` option of the modules section to all module blueprints automatically: https://github.com/medienbaecker/kirby-modules/blob/master/index.php#L44

Of course you can also use a pages section and set it manually:

```yml
modules:
  type: pages
  info: '{{ page.moduleName }}'
  parent: page.find("modules")
  create:
    - module.text
    - module.images
```
